### PR TITLE
ci: call test-vhd-no-egress github workflow from create-release-branch

### PR DESCRIPTION
**Pull request by christinalau0**
**Reason for Change**:

Update the create-release-branch Github action to call the new test-vhd-no-egress Github action. With this change, the create-release-branch Github action will first run full test suites on the current k8s versions, with no outbound connection. If passed, then it will create the release branch and changelog PR.

See example run create-release-branch: https://github.com/christinalau0/aks-engine-azurestack/actions/runs/4494630778/jobs/7907894274
See example run test-vhd-no-egress: https://github.com/christinalau0/aks-engine-azurestack/actions/runs/4494961470/jobs/7908080869

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by christinalau0** [comment]
DNM until example runs are complete.

**Comment by christinalau0** [comment]
Example run clean, good to merge: https://github.com/christinalau0/aks-engine-azurestack/actions/runs/4494630778/jobs/7907894274

**Review by jadarsie — APPROVED** [review]

**Pull request merged**
