### PR TITLE
chore: support Kubernetes v1.27.6

### PR DESCRIPTION
**Pull request by christinalau0**
**Reason for Change**:

- add [k8s v1.27.6](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.27.md#changelog-since-v1260)
  - many flags removed in k8s v1.27, will come in subsequent PR
- add [azure-cloud-controller-manager v1.27.9](https://github.com/kubernetes-sigs/cloud-provider-azure/releases/tag/v1.27.9)
- add [azure-cloud-node-manager v1.27.4](https://github.com/kubernetes-sigs/cloud-provider-azure/releases/tag/v1.27.4)
- bumped all test workflow k8s versions

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by christinalau0** [comment]
Validated the new components are reachable/exist by the VHD buddy pipeline: https://msazure.visualstudio.com/One/_build/results?buildId=81025559&view=results

Currently v1.27 clusters fail to deploy because a kubelet flag must be removed. Will make a separate PR to remove flags and feature gates, to go in before this one.

**Review by jadarsie — APPROVED** [review]

**Pull request merged**
